### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by mluis** [loicdescotte/vote4music#4]
When I run play deps it shows OK for all others but not for these ones:

~ *****************************************************************************
~ WARNING: These dependencies are missing, your application may not work properly (use --verbose for details),
~
~   mysql->mysql-connector-java 5.1.20
~   org.jboss.netty->netty 3.4.2.Final
~ *****************************************************************************

Could you please update me on what to do in order to solve this issue?
Thank you.

**Comment by loicdescotte** [comment]
Hello 
What version or play are you using ?

**Comment by mluis** [comment]
1.2.5  play! master-f4e9637

**Comment by loicdescotte** [comment]
For me it's working. Do you have proxy issues?

[descottl@descottl vote4music]$ ~/dev/play-1.2.5/play deps
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ | |/ _' | || |_|
~ |  **/|_|__**|__ (_)
~ |_|            |__/  
~
~ play! 1.2.5, http://www.playframework.org
~
~ Resolving dependencies using /home/descottl/dev/vote4music/conf/dependencies.yml,
~
~   com.googlecode.lambdaj->lambdaj 2.2 (from mavenCentral)
~   org.hamcrest->hamcrest-all 1.1 (from mavenCentral)
~   org.objenesis->objenesis 1.2 (from mavenCentral)
~   play->html5validation 1.2 (from playContributedModules)
~
~ Downloading required dependencies,
~
~   downloaded http://repo1.maven.org/maven2/com/googlecode/lambdaj/lambdaj/2.2/lambdaj-2.2-sources.jar  
~
~ Installing resolved dependencies,
~
~   lib/lambdaj-2.2.jar
~   modules/html5validation-1.2
~   modules/secure -> /home/descottl/dev/play-1.2.5/modules/secure
~   lib/hamcrest-all-1.1.jar
~   lib/objenesis-1.2.jar
~
~ Done!
~
