### ISSUE TITLE
Deploy project using play v2.0

### ISSUE THREAD

**Issue by pgaref** [loicdescotte/vote4music#5]
Hello,

Is it possible to deploy the project using play-2.0? Since there is no project folder and sbt files I am not sure how this could work. I just started experimenting with play and I wanted to test the project but got no luck. Let me know if I got something wrong.

Thanks,
Panagiotis

**Comment by loicdescotte** [comment]
Hi,
Unfortunately Play 2 is not retro compatible.
It's a Play 1.x project only.  If you're looking to Play 2 samples there are good ones in the Typesafe Activator templates, e.g. https://typesafe.com/activator/template/computer-database-java

**Comment by pgaref** [comment]
Thanks for the reply. I will try the typesafe templates instead.
